config/routes.rb
Rails.application.routes.draw do
  get 'questions/schools', to: 'questions#schools'
  get "school_questions/:school", to: "questions#questions_by_school"
  get "user_answers/:user_id", to: "school_answers#user_already_answered"
  get "case_by_user/:user_id", to: "cases#case_by_user"
  get "users/school/:school", to: "users#users_by_school"
  resources :schools
  resources :school_answers
  resources :questions
  resources :cases
  post "sessions/create"
  get "sessions/destroy"
  resources :users
  resources :tickets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: %i[ show edit update destroy ]
  skip_before_action :validade_token, only: %i[ index case_by_user ]
  
  # GET /cases or /cases.json
def index
  cases = Case.all.map do |c|
    c.as_json.merge({
      images: c.images.map { |img| url_for(img) },
      owner_email: c.user.email
    })
  end

  render json: cases
end

  # GET /cases/1 or /cases/1.json
  def show
    render json: @case.as_json.merge({
      images: @case.images.map { |img| url_for(img) },
      owner_email: @case.user.email
    })
  end

  # GET /cases/new
  def new
    @case = Case.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases or /cases.json
  def create
    @user = User.find_by(
      id: case_params[:user_id], 
    )
   
    @case = Case.new(
      user: @user,
      description: case_params[:description], 
      institution_answer: case_params[:institution_answer], 
      images: case_params[:images]
    )

    respond_to do |format|
      if @case.save
        format.html { redirect_to case_url(@case), notice: "Case was successfully created." }
        format.json { render :show, status: :created, location: @case }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cases/1 or /cases/1.json
  def update
    respond_to do |format|
      if @case.update(case_params)
        format.html { redirect_to case_url(@case), notice: "Case was successfully updated." }
        format.json { render :show, status: :ok, location: @case }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cases/1 or /cases/1.json
  def destroy
    @case.destroy!

    respond_to do |format|
      format.html { redirect_to cases_url, notice: "Case was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def case_by_user
    @case = Case.find_by(user_id: params[:user_id])
    if @case
      render json: @case.as_json.merge({
        images: @case.images.map { |img| url_for(img) },
        owner_email: @case.user.email
      })
    else
      render json: { error: "Case not found for user #{params[:user_id]}" }, status: :not_found
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Case.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def case_params
      params.require(:case).permit(:user_id, :description, :institution_answer, images: [])

    end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/_case.html.erb
<div id="<%= dom_id case %>">
  <p>
    <strong>User:</strong>
    <%= case.user_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= case.description %>
  </p>

  <p>
    <strong>Institution answer:</strong>
    <%= case.institution_answer %>
  </p>

</div>

app/views/cases/_form.html.erb
<%= form_with(model: case) do |form| %>
  <% if case.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
        <% case.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :institution_answer, style: "display: block" %>
    <%= form.text_area :institution_answer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
<% content_for :title, "Editing case" %>

<h1>Editing case</h1>

<%= render "form", case: @case %>

<br>

<div>
  <%= link_to "Show this case", @case %> |
  <%= link_to "Back to cases", cases_path %>
</div>

app/views/cases/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Cases" %>

<h1>Cases</h1>

<div id="cases">
  <% @cases.each do |case| %>
    <%= render case %>
    <p>
      <%= link_to "Show this case", case %>
    </p>
  <% end %>
</div>

<%= link_to "New case", new_case_path %>

app/views/cases/new.html.erb
<% content_for :title, "New case" %>

<h1>New case</h1>

<%= render "form", case: @case %>

<br>

<div>
  <%= link_to "Back to cases", cases_path %>
</div>

app/views/cases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @case %>

<div>
  <%= link_to "Edit this case", edit_case_path(@case) %> |
  <%= link_to "Back to cases", cases_path %>

  <%= button_to "Destroy this case", @case, method: :delete %>
</div>