config/routes.rb
Rails.application.routes.draw do
  get 'questions/schools', to: 'questions#schools'
  get "school_questions/:school", to: "questions#questions_by_school"
  get "user_answers/:user_id", to: "school_answers#user_already_answered"
  get "case_by_user/:user_id", to: "cases#case_by_user"
  get "users/school/:school", to: "users#users_by_school"
  resources :schools
  resources :school_answers
  resources :questions
  resources :cases
  post "sessions/create"
  get "sessions/destroy"
  resources :users
  resources :tickets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/school.rb
class School < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[ show edit update destroy ]
  skip_before_action :validade_token

  # GET /schools or /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1 or /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_url(@school), notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to school_url(@school), notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy!

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school) do |form| %>
  <% if school.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/_school.html.erb
<div id="<%= dom_id school %>">
  <p>
    <strong>Name:</strong>
    <%= school.name %>
  </p>

</div>

app/views/schools/edit.html.erb
<% content_for :title, "Editing school" %>

<h1>Editing school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Show this school", @school %> |
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Schools" %>

<h1>Schools</h1>

<div id="schools">
  <% @schools.each do |school| %>
    <%= render school %>
    <p>
      <%= link_to "Show this school", school %>
    </p>
  <% end %>
</div>

<%= link_to "New school", new_school_path %>

app/views/schools/new.html.erb
<% content_for :title, "New school" %>

<h1>New school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @school %>

<div>
  <%= link_to "Edit this school", edit_school_path(@school) %> |
  <%= link_to "Back to schools", schools_path %>

  <%= button_to "Destroy this school", @school, method: :delete %>
</div>